In [13]:
import pandas as pd
import yfinance as yf
import datetime as dt
import numpy as np

In [3]:
end = dt.datetime.now()
start = dt.datetime(2012,1,1)
start,end

(datetime.datetime(2012, 1, 1, 0, 0),
 datetime.datetime(2026, 1, 12, 19, 8, 51, 870159))

In [4]:
stockList = ['HDFCBANK','ICICIBANK','SBIN','KOTAKBANK']
stocks = [i + '.NS' for i in stockList]
stocks

['HDFCBANK.NS', 'ICICIBANK.NS', 'SBIN.NS', 'KOTAKBANK.NS']

In [5]:
df = yf.download(tickers=stocks, start=start, end=end)

[*********************100%***********************]  4 of 4 completed

In [6]:
df = df.stack(level='Ticker')

C:\Users\shaba\AppData\Local\Temp\ipykernel_13960\457774305.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df = df.stack(level='Ticker')

In [7]:
df = df.unstack()
df.head()

Price            Close                                              High  \
Ticker     HDFCBANK.NS ICICIBANK.NS KOTAKBANK.NS     SBIN.NS HDFCBANK.NS
Date
2012-01-02   95.029961   108.549957   208.759109  137.711975   95.686717
2012-01-03   97.768318   113.108269   222.717636  144.311356   98.157922
2012-01-04   98.692238   115.804276   217.470840  143.499130   99.059584
2012-01-05   98.770164   116.583504   220.490204  143.194519   99.449193
2012-01-06  100.918533   117.144485   224.697556  141.527756  101.775663

Price                                                    Low               \
Ticker     ICICIBANK.NS KOTAKBANK.NS     SBIN.NS HDFCBANK.NS ICICIBANK.NS
Date
2012-01-02   109.009682   214.575161  138.418456   93.393623   106.765596
2012-01-03   113.606954   224.549064  144.679398   95.731248   109.866811
2012-01-04   116.723738   222.247425  145.009383   95.920488   113.825122
2012-01-05   117.939307   221.752405  145.402784   98.024350   115.165355
2012-01-06   118.905462   228.187180  144.476339   97.723787   113.451086

Price                                      Open                            \
Ticker     KOTAKBANK.NS     SBIN.NS HDFCBANK.NS ICICIBANK.NS KOTAKBANK.NS
Date
2012-01-02   206.952424  136.337097   95.486351   107.552586   214.278168
2012-01-03   210.615294  139.010675   96.042929   109.866811   210.615294
2012-01-04   216.060136  141.735064   98.380556   114.292642   222.247425
2012-01-05   213.857419  142.145390   98.848087   116.100395   217.792540
2012-01-06   218.287519  140.284019   98.180177   115.632839   218.287519

Price                       Volume
Ticker         SBIN.NS HDFCBANK.NS ICICIBANK.NS KOTAKBANK.NS   SBIN.NS
Date
2012-01-02  137.826191     7029996     14927627       964766  14464990
2012-01-03  139.095275     6878476     18500311      2153928  21341020
2012-01-04  144.848626     9742956     32952243      1220318  22241630
2012-01-05  143.494886     6761212     23203350      2796070  21344840
2012-01-06  141.718129     7954444     22273933      1879586  21137420

In [8]:
close = df.Close
close[close.index > end - dt.timedelta(days=100)].describe()

Ticker  HDFCBANK.NS  ICICIBANK.NS  KOTAKBANK.NS      SBIN.NS
count     70.000000     70.000000     70.000000    70.000000
mean     989.735713   1372.305720   2141.295717   952.429284
std       15.204611     23.100878     38.712185    38.940018
min      936.950012   1320.400024   2069.899902   858.250000
25%      984.537506   1358.450043   2106.974915   937.687500
50%      991.899994   1370.350037   2146.050049   963.200012
75%     1000.012497   1383.849976   2163.699951   974.087494
max     1009.500000   1436.599976   2225.600098  1018.900024

In [9]:
import plotly.offline as pyo
pyo.init_notebook_mode(connected=True)

pd.options.plotting.backend = 'plotly'

In [10]:
close.plot()

In [11]:
close['SBIN.NS'].pct_change().plot(kind='hist',nbins=50)

In [12]:
close['SBIN.NS'].pct_change().agg(['min','max'])

min   -0.144040
max    0.276872
Name: SBIN.NS, dtype: float64

In [16]:
test = close
test['shift'] = test['HDFCBANK.NS'].shift(1)
test.head()

C:\Users\shaba\AppData\Local\Temp\ipykernel_13960\2109729019.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Ticker      HDFCBANK.NS  ICICIBANK.NS  KOTAKBANK.NS     SBIN.NS      shift
Date
2012-01-02    95.029961    108.549957    208.759109  137.711975        NaN
2012-01-03    97.768318    113.108269    222.717636  144.311356  95.029961
2012-01-04    98.692238    115.804276    217.470840  143.499130  97.768318
2012-01-05    98.770164    116.583504    220.490204  143.194519  98.692238
2012-01-06   100.918533    117.144485    224.697556  141.527756  98.770164

In [19]:
test.dropna(inplace=True)

C:\Users\shaba\AppData\Local\Temp\ipykernel_13960\1474856954.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [20]:
test['log_value'] = np.log(test['HDFCBANK.NS']/test['shift'])
test.head()

C:\Users\shaba\AppData\Local\Temp\ipykernel_13960\3706254577.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Ticker,HDFCBANK.NS,ICICIBANK.NS,KOTAKBANK.NS,SBIN.NS,shift,log_value
Date,,,,,,
2012-01-03,97.768318,113.108269,222.717636,144.311356,95.029961,0.028408
2012-01-04,98.692238,115.804276,217.470840,143.499130,97.768318,0.009406
2012-01-05,98.770164,116.583504,220.490204,143.194519,98.692238,0.000789
2012-01-06,100.918533,117.144485,224.697556,141.527756,98.770164,0.021518
2012-01-09,101.452858,116.536713,224.326309,138.524185,100.918533,0.005281

In [26]:
test['change'] = test['log_value'].cumsum()

C:\Users\shaba\AppData\Local\Temp\ipykernel_13960\870255274.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [27]:
test.head()

Ticker,HDFCBANK.NS,ICICIBANK.NS,KOTAKBANK.NS,SBIN.NS,shift,log_value,change
Date,,,,,,,
2012-01-03,97.768318,113.108269,222.717636,144.311356,95.029961,0.028408,0.028408
2012-01-04,98.692238,115.804276,217.470840,143.499130,97.768318,0.009406,0.037814
2012-01-05,98.770164,116.583504,220.490204,143.194519,98.692238,0.000789,0.038603
2012-01-06,100.918533,117.144485,224.697556,141.527756,98.770164,0.021518,0.060121
2012-01-09,101.452858,116.536713,224.326309,138.524185,100.918533,0.005281,0.065402

In [28]:
test['change'].plot()

In [40]:
test['change_pct'] = (np.exp(test['change'])-1)*100
test.head()

C:\Users\shaba\AppData\Local\Temp\ipykernel_13960\3061765142.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Ticker,HDFCBANK.NS,ICICIBANK.NS,KOTAKBANK.NS,SBIN.NS,shift,log_value,change,change_pct
Date,,,,,,,,
2012-01-03,97.768318,113.108269,222.717636,144.311356,95.029961,0.028408,0.028408,2.881573
2012-01-04,98.692238,115.804276,217.470840,143.499130,97.768318,0.009406,0.037814,3.853813
2012-01-05,98.770164,116.583504,220.490204,143.194519,98.692238,0.000789,0.038603,3.935815
2012-01-06,100.918533,117.144485,224.697556,141.527756,98.770164,0.021518,0.060121,6.196543
2012-01-09,101.452858,116.536713,224.326309,138.524185,100.918533,0.005281,0.065402,6.758813

In [41]:
test['change_pct'].plot()